name: Publish Github Package

on:
  push:
    tags:
      - '**'
  workflow_dispatch:




jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assemble project
        run: ./gradlew assemble --stacktrace -PUSERNAME=${{ secrets.USERNAME }} -PTOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub
        run: ./gradlew publish --stacktrace -PUSERNAME=${{ secrets.USERNAME }} -PTOKEN=${{ secrets.GITHUB_TOKEN }}